development:
  adapter: postgresql
  database: firstblogdev
  username: postgres
  password: abcd1234
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: firstblogtest
  username: postgres
  password: abcd1234
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: firstblogprod
  username: postgres
  password: abcd1234
  host: localhost
  pool: 5
  timeout: 5000